# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-08-30 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220830_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 6, 35, 14, 342049, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 6, 35, 14, 341382, tzinfo=utc)),
        ),
    ]
