# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-08-31 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220830_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 0, 17, 49, 477701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 0, 17, 49, 477131, tzinfo=utc)),
        ),
    ]
